package org.launchcode.becflix.models;

public enum Year {


    MDCCCLXXXVIII("1888"),
    MDCCCLXXXIX("1889"),
    MDCCCXC("1890"),
    MDCCCXCI("1891"),
    MDCCCXCII("1892"),
    MDCCCXCIII("1893"),
    MDCCCXCIV("1894"),
    MDCCCXCV("1895"),
    MDCCCXCVI("1896"),
    MDCCCXCVII("1897"),
    MDCCCXCVIII("1898"),
    MDCCCXCIX("1899"),
    MCM("1900");
    /*
    MCMI
    MCMII
            MCMIII
    MCMIV
            MCMV
    MCMVI
            MCMVII
    MCMVIII
            MCMIX
    MCMX
            MCMXI
    MCMXII
            MCMXIII
    MCMXIV
            MCMXV
    MCMXVI
            MCMXVII
    MCMXVIII
            MCMXIX
    MCMXX
            MCMXXI
    MCMXXII
            MCMXXIII
    MCMXXIV
            MCMXXV
    MCMXXVI
            MCMXXVII
    MCMXXVIII
            MCMXXIX
    MCMXXX
            MCMXXXI
    MCMXXXII
            MCMXXXIII
    MCMXXXIV
            MCMXXXV
    MCMXXXVI
            MCMXXXVII
    MCMXXXVIII
            MCMXXXIX
    MCMXL
            MCMXLI
    MCMXLII
            MCMXLIII
    MCMXLIV
            MCMXLV
    MCMXLVI
            MCMXLVII
    MCMXLVIII
            MCMXLIX
    MCML
            MCMLI
    MCMLII
            MCMLIII
    MCMLIV
            MCMLV
    MCMLVI
            MCMLVII
    MCMLVIII
            MCMLIX
    MCMLX
            MCMLXI
    MCMLXII
            MCMLXIII
    MCMLXIV
            MCMLXV
    MCMLXVI
            MCMLXVII
    MCMLXVIII
            MCMLXIX
    MCMLXX
            MCMLXXI
    MCMLXXII
            MCMLXXIII
    MCMLXXIV
            MCMLXXV
    MCMLXXVI
            MCMLXXVII
    MCMLXXVIII
            MCMLXXIX
    MCMLXXX
            MCMLXXXI
    MCMLXXXII
            MCMLXXXIII
    MCMLXXXIV
            MCMLXXXV
    MCMLXXXVI
            MCMLXXXVII
    MCMLXXXVIII
            MCMLXXXIX
    MCMXC
            MCMXCI
    MCMXCII
            MCMXCIII
    MCMXCIV
            MCMXCV
    MCMXCVI
            MCMXCVII
    MCMXCVIII
            MCMXCIX
    MM
            MMI
    MMII
            MMIII
    MMIV
            MMV
    MMVI
            MMVII
    MMVIII
            MMIX
    MMX
            MMXI
    MMXII
            MMXIII
    MMXIV
            MMXV
    MMXVI
            MMXVII
    MMXVIII
            MMXIX
    MMXX
            MMXXI
    MMXXII
            MMXXIII
    MMXXIV
            MMXXV
    MMXXVI
            MMXXVII
    MMXXVIII
            MMXXIX
    MMXXX
            MMXXXI
    MMXXXII
            MMXXXIII
    MMXXXIV
            MMXXXV
    MMXXXVI
            MMXXXVII
    MMXXXVIII
            MMXXXIX
    MMXL
            MMXLI
    MMXLII
            MMXLIII
    MMXLIV
            MMXLV
    MMXLVI
            MMXLVII
    MMXLVIII
            MMXLIX
    MML
            MMLI
    MMLII
            MMLIII
    MMLIV
            MMLV
    MMLVI
            MMLVII
    MMLVIII
            MMLIX
    MMLX
            MMLXI
    MMLXII
            MMLXIII
    MMLXIV
            MMLXV
    MMLXVI
            MMLXVII
    MMLXVIII
            MMLXIX
    MMLXX
            MMLXXI
    MMLXXII
            MMLXXIII
    MMLXXIV
            MMLXXV
    MMLXXVI
            MMLXXVII
    MMLXXVIII
            MMLXXIX
    MMLXXX
            MMLXXXI
    MMLXXXII
            MMLXXXIII
    MMLXXXIV
            MMLXXXV
    MMLXXXVI
            MMLXXXVII
    MMLXXXVIII
            MMLXXXIX
    MMXC
            MMXCI
    MMXCII
            MMXCIII
    MMXCIV
            MMXCV
    MMXCVI
            MMXCVII
    MMXCVIII
            MMXCIX
    MMC
            MMCI
    MMCII
            MMCIII
    MMCIV
            MMCV
    MMCVI
            MMCVII
    MMCVIII
            MMCIX
    MMCX
            MMCXI
    MMCXII
            MMCXIII
    MMCXIV
            MMCXV
*/


    private final String displayYear;

    Year(String displayYear) {
        this.displayYear = displayYear;
    }

    public String getDisplayYear() {
        return displayYear;
    }

}
